sourceController:
  image: ghcr.io/fluxcd/source-controller:v0.24.2
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 64Mi
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  args: 
    - --events-addr=
    - --watch-all-namespaces=true
    - --log-level=info
    - --log-encoding=json
    - --enable-leader-election
    - --storage-path=/data
    - --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.

helmController:
  image: ghcr.io/fluxcd/helm-controller:v0.20.1
  imagePullPolicy: IfNotPresent
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 64Mi
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  args: 
    - --events-addr=
    - --watch-all-namespaces=true
    - --log-level=info
    - --log-encoding=json
    - --enable-leader-election
    - --concurrent=8

imageAutomationController:
  image: ghcr.io/fluxcd/image-automation-controller:v0.22.0
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 64Mi
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  args:
    - --events-addr=
    - --watch-all-namespaces=true
    - --log-level=info
    - --log-encoding=json
    - --enable-leader-election

imageReflectorController:
  image: ghcr.io/fluxcd/image-reflector-controller:v0.17.2
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 64Mi
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  args:
    - --events-addr=
    - --watch-all-namespaces=true
    - --log-level=info
    - --log-encoding=json
    - --enable-leader-election
