kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: {{ .Values.gateway.name }}
spec:
  gatewayClassName: {{ .Values.gateway.class }}
  addresses:
  - type: NamedAddress
    value: {{ .Values.gateway.addressName }}
  listeners:
{{ toYaml .Values.listeners | indent 4 }}
