---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nfs-server-gcp.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
