apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.cloudflare.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.name }}
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.clusterIssuer.cloudflare.email }}
          apiTokenSecretRef:
            name: {{ .Values.clusterIssuer.cloudflare.APIToken.name }}
            key: {{ .Values.clusterIssuer.cloudflare.APIToken.key }}

    