apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    role: wp
spec:
  replicas: 1 # must not exceed 1
  selector:
    matchLabels:
      app: redis
      tier: admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        tier: admin
    spec:
      containers:
      - name: redis
        image: redis:{{ .Values.redis.version }}
        ports:
        - containerPort: 6379
          name: redis-svc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-svc
  selector:
    app: redis
    tier: admin
  type: ClusterIP
