apiVersion: v1
kind: Secret
metadata:
  name: ssh-user-conf-secret
type: Opaque
stringData:
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEAx1xj43/jhzCiwzZAxv2Jni9JUfOHkim4AZGdsG118 user@host
#data:
#  authorized_keys: |
#    c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUVBeDF4ajQzL2poekNpd3paQXh2MkpuaTlKVWZPSGtpbTRBWkdkc0cxMTgganNASmV0Sm9leTIwCg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-options-configmap
data:
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_MEMORY_LIMIT', '64M');
    @ini_set( 'upload_max_size', '64M' );
    @ini_set( 'post_max_size', '64M');
    @ini_set( 'max_execution_time', '300' );
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-options-configmap
data:
  custom.ini: |
    session.save_handler = redis
    session.save_path = "tcp://redis.default.svc.cluster.local:6379"
