name: Build cluster-issuer helm chart
on:
  push:
    branches:
      - main
    paths:
      - "charts/cluster-issuer/**"
      - ".github/workflows/cluster-issuer.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "charts/cluster-issuer/**"
      - ".github/workflows/cluster-issuer.yaml"
  
jobs:
  cluster-issuer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: pulling the branch
      with:
        fetch-depth: 50

    - name: Linting Helm
      run: |
        helm lint charts/cluster-issuer/
    - name: Setup git
      if: github.event_name == 'push'
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Get new chart version
      if: github.event_name == 'push'
      run: |
        echo "CHART_VERSION=$(cat charts/cluster-issuer/Chart.yaml | grep version | head -1 | sed -e "s/version: //" | \
        awk -F'[.]'  '{ major=$1;minor=$2;patch=$3;patch += 1;minor += patch / 20;patch = patch % 20;printf( "%d.%d.%d\n", major, minor, patch );}' )" \
        >> $GITHUB_ENV

    - name: Update chart version
      if: github.event_name == 'push'
      run: |
        sed -i 's/^version: .*$/version: '"$CHART_VERSION"'/1' charts/cluster-issuer/Chart.yaml

    - name: Debug
      if: github.event_name == 'push'
      id: version
      run: |
        echo "::set-output name=CHART_VERSION::$(echo $CHART_VERSION)"
    - name: Generate changelog
      if: github.event_name == 'push'
      id: Changelog
      uses: metcalfc/changelog-generator@v1.0.0
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      if: github.event_name == 'push'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "cluster-issuer-${{ env.CHART_VERSION }}"
        release_name: "cluster-issuer-${{ env.CHART_VERSION }}"
        body: ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Update chart version in remote repo
      if: github.event_name == 'push'
      run: |
        git pull origin main
        git add charts/cluster-issuer/Chart.yaml
        git commit -m "[AUTO] update chart version"
        git push

    - name: Copy chart to gh-pages branch
      if: github.event_name == 'push'
      run: |
        git fetch origin gh-pages
        git checkout gh-pages -f
        git checkout main charts/cluster-issuer/ -f
    - name: Package and indexing Chart
      if: github.event_name == 'push'
      run: |
        helm package charts/cluster-issuer/
        helm repo index .
    - name: Commit to branch
      if: github.event_name == 'push'
      run: |
        git restore --staged charts/cluster-issuer/
        git add index.yaml cluster-issuer*.tgz
        git commit -m "[AUTO] New cluster-issuer Chart version"
        git push
