name: Build nfs-server-gcp helm chart
on:
  push:
    branches:
      - main
    paths:
      - "charts/nfs-server-gcp/**"
      - ".github/workflows/nfs-server-gcp.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "charts/nfs-server-gcp/**"
      - ".github/workflows/nfs-server-gcp.yaml"
  
jobs:
  nfs-server-gcp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: pulling the branch
      with:
        fetch-depth: 50

    - name: Linting Helm
      run: |
        helm lint charts/nfs-server-gcp/

    - name: Setup git
      if: github.event_name == 'push'
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Get new chart version
      if: github.event_name == 'push'
      run: |
        echo "NFSSERVER_VERSION=$(cat charts/nfs-server-gcp/Chart.yaml | grep version | head -1 | sed -e "s/version: //" | \
        awk -F'[.]'  '{ major=$1;minor=$2;patch=$3;patch += 1;minor += patch / 20;patch = patch % 20;printf( "%d.%d.%d\n", major, minor, patch );}' )" \
        >> $GITHUB_ENV

    - name: Update chart version
      if: github.event_name == 'push'
      run: |
        sed -i 's/^version: .*$/version: '"$NFSSERVER_VERSION"'/1' charts/nfs-server-gcp/Chart.yaml

    - name: Debug
      if: github.event_name == 'push'
      id: version
      run: |
        echo "::set-output name=NFSSERVER_VERSION::$(echo $NFSSERVER_VERSION)"

    - name: Generate changelog
      if: github.event_name == 'push'
      id: Changelog
      uses: metcalfc/changelog-generator@v1.0.0
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      if: github.event_name == 'push'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "nfs-server-gcp-${{ env.NFSSERVER_VERSION }}"
        release_name: "nfs-server-gcp-${{ env.NFSSERVER_VERSION }}"
        body: ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Update chart version in remote repo
      if: github.event_name == 'push'
      run: |
        git add charts/nfs-server-gcp/Chart.yaml
        git commit -m "[AUTO] update chart version"
        git push

    - name: Copy chart to gh-pages branch
      if: github.event_name == 'push'
      run: |
        git fetch origin gh-pages
        git checkout gh-pages -f
        git checkout main charts/nfs-server-gcp/ -f

    - name: Package and indexing Chart
      if: github.event_name == 'push'
      run: |
        helm dependency update charts/nfs-server-gcp/
        helm package charts/nfs-server-gcp/
        helm repo index .

    - name: Commit to branch
      if: github.event_name == 'push'
      run: |
        git restore --staged charts/nfs-server-gcp/
        git add index.yaml nfs-server-gcp*.tgz
        git commit -m "[AUTO] New nfs-server-gcp Chart version"
        git push
